# Generated by Django 4.2.12 on 2024-05-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_presence_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateTimeField(verbose_name=6),
        ),
    ]
