# Generated by Django 4.2.12 on 2024-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_presence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='present',
            field=models.CharField(default='Présent', max_length=150),
        ),
    ]
