# Generated by Django 4.2.12 on 2024-05-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_presence_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='present',
            field=models.CharField(default='Non détecté(e)', max_length=150),
        ),
    ]
